"""empty message

Revision ID: 7cda245dbdde
Revises: 
Create Date: 2024-09-20 12:53:05.414267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cda245dbdde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('u_id', sa.String(length=128), nullable=False),
    sa.Column('u_name', sa.Float(), nullable=True),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('u_id')
    )
    op.create_table('cpu',
    sa.Column('cpu_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cpu_count', sa.Integer(), nullable=True),
    sa.Column('cpu_freq', sa.Float(), nullable=True),
    sa.Column('cpu_utilization', sa.Float(), nullable=True),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.Column('u_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['u_id'], ['user.u_id'], ),
    sa.PrimaryKeyConstraint('cpu_id')
    )
    op.create_table('disk',
    sa.Column('d_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('d_total', sa.Float(), nullable=True),
    sa.Column('d_used', sa.Float(), nullable=True),
    sa.Column('d_free', sa.Float(), nullable=True),
    sa.Column('d_utilization', sa.Float(), nullable=True),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.Column('u_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['u_id'], ['user.u_id'], ),
    sa.PrimaryKeyConstraint('d_id')
    )
    op.create_table('gpu',
    sa.Column('g_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('g_name', sa.String(length=128), nullable=True),
    sa.Column('g_memory_total', sa.Float(), nullable=True),
    sa.Column('g_memory_used', sa.Float(), nullable=True),
    sa.Column('g_memory_free', sa.Float(), nullable=True),
    sa.Column('g_utilization', sa.Float(), nullable=True),
    sa.Column('g_count', sa.Integer(), nullable=True),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.Column('u_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['u_id'], ['user.u_id'], ),
    sa.PrimaryKeyConstraint('g_id')
    )
    op.create_table('memory',
    sa.Column('m_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('m_total', sa.Float(), nullable=True),
    sa.Column('m_used', sa.Float(), nullable=True),
    sa.Column('m_free', sa.Float(), nullable=True),
    sa.Column('m_utilization', sa.Float(), nullable=True),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.Column('u_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['u_id'], ['user.u_id'], ),
    sa.PrimaryKeyConstraint('m_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memory')
    op.drop_table('gpu')
    op.drop_table('disk')
    op.drop_table('cpu')
    op.drop_table('user')
    # ### end Alembic commands ###
