"""empty message

Revision ID: 81f6d123adc4
Revises: 7cda245dbdde
Create Date: 2024-09-20 13:59:36.617578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '81f6d123adc4'
down_revision = '7cda245dbdde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('u_name',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('u_name',
               existing_type=sa.String(length=128),
               type_=mysql.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
